### ISSUE TITLE
Question: Why did you use [PURE] annotation? And How do you use the Test Coverage lib?

### ISSUE THREAD

**Issue by ltlombardi** [nekronos/ResultSharp#4]
For what I've gathered, it's a deprecated utility https://www.infoq.com/news/2019/01/pure-attribute-net-core/ 

1. Do you guys use some kind of external tool that use it somehow?
2. I also noticed the project has a reference for "coverlet.collector". Do you run it via command line, or do you use something more convenient?
3. What about the coverage result file "coverage.cobertura.xml". Do you use a viewer?

**Comment by nekronos** [comment]
Using `[Pure]` is just a habit from dealing with the mutable nature of C#, where `[Pure]` is basically just there for readability. But in this library we are using readonly structs, so I guess using `[Pure]` in this case is pointless and noisy anyways.

A reference for `coverlet.collector` is added by default in the Visual Studio XUnit test project template. So it is not in use and I don`t see a need yet as this library is rather simple.

Thanks for submitting these questions, I will cleanup the code and project references 👍🏻 💯
